### ISSUE TITLE
[Suggestion] Add Steamid64 support for !giveitem 

### ISSUE THREAD

**Issue by MaceUD** [TheCrunchy/FixPlayerCommand#10]
Hi and thanks for the additions !

It would be nice to have the steamid64 support to give items with the command.
Some players change their names and in the end I get errors when I try to give them some items.

Since SEdiscordbridge gives SteamID64 now, it would be useful to be able to use : 
`!giveitem SteamID64 ...` in addition to `!giveitem <PlayerName>...`

Would save me some time :)

Thanks for reading!

**Comment by TheCrunchy** [comment]
put the name in "", it finds the online player with that steam name
