### ISSUE TITLE
[Suggestion] Add PhysicalGunObjects & Ammos to !giveitems

### ISSUE THREAD

**Issue by MaceUD** [TheCrunchy/FixPlayerCommand#11]
Hey, me again ahah

I saw in the code that !giveitem works for Ingots, Ores and Components only.

It would be nice if we could have it for PhysicalGunObjects (Guns, Welding tools, Grinding Toold) and Ammos. Sometimes due to server crash I find myself needing to give Elite tools back to players that lost them. And I can't right now :/

Sincerely,

**Comment by TheCrunchy** [comment]
Added, use object for guns/tools and ammo for magazines
