### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by dorimanx** [TheCrunchy/FixPlayerCommand#2]
Hi, please allow player to transfer money from his virtual account to other player.
!eco giveplayer
right now only admin can use this.
Players like to give money to other players, for help, or bribe haha.

Thanks.

**Comment by TheCrunchy** [comment]
Added, it will need enabling in the config, if users have issues with player names not working in the commands, enabling the update task might help. 

!eco pay playernameorid amount

**Comment by dorimanx** [comment]
thank you! awesome work!
