### ISSUE TITLE
[BUG] !listids don't work with SEDB

### ISSUE THREAD

**Issue by MaceUD** [TheCrunchy/FixPlayerCommand#4]
Hi, when I use !listids in the se discord bridge channel, only 1 output is given, and ingame it workds properly.

See screenshots :

![Capture](https://user-images.githubusercontent.com/64008256/81470906-c8c74280-91ed-11ea-9bb4-fde764545811.PNG)
![Capture2](https://user-images.githubusercontent.com/64008256/81470907-c9f86f80-91ed-11ea-9187-d8c973ac0c1d.PNG)

Sincerely

**Comment by TheCrunchy** [comment]
Should be fixed
