### ISSUE TITLE
[Suggestion] !giveitem command ignore free space

### ISSUE THREAD

**Issue by MaceUD** [TheCrunchy/FixPlayerCommand#5]
Hey !

Currently, the `!giveitem command` will give the items you want IF the players has the capacity to receive it. I tested to give `!giveitem "Mace Windu" Ore Ice 99999` and it did not work but still showed me the output.

It would be nice if the command would give the items even if the player don't have the free space.
Yes player would be overloaded but that's an admin command so it is not much an issue.

Sincerely,

**Comment by TheCrunchy** [comment]
Will look into force adding the items, for now i have added an error if the items cant be added

**Comment by dorimanx** [comment]
I know it's possible, as Reward Plugin is doing it, all the time. items just pushed no matter what to personal storage.
This is important for player rewarding system.
Thanks.

**Comment by TheCrunchy** [comment]
Added, put true at the end of the command to force add the items
