### ISSUE TITLE
[Suggestion] Allow !rename command to rename a targeted grid

### ISSUE THREAD

**Issue by MaceUD** [TheCrunchy/FixPlayerCommand#6]
Hey,

It would be easier if players could rename a grid without having to know it's name but just by aiming at it.

Player would aim the grid he wants to rename, then use `!rename <StringNewName>`

This would be so much useful !

Sincerely,

**Comment by TheCrunchy** [comment]
Renaming the grid they are looking at can be problematic if there is a grid attached as it will also rename that grid

**Comment by MaceUD** [comment]
Maybe there is a way to find if a grid is attached and so either : 
- Convert only the targeted grid
- Not convert anything and gives errors to sender

But idk the code of the game so it's a supposition :)
