### ISSUE TITLE
!eco deposit command some tuning needed. :)

### ISSUE THREAD

**Issue by dorimanx** [TheCrunchy/FixPlayerCommand#7]
Hi,
Players reporting that when they look at their grid that parked inside their faction base, connected by connector or just landing gear!
And they type !eco deposit
All credits in all grids at same base connected or just parked with landing gear, will be transferred to account of player, that requested the deposit.

So, suggestion is to make sure that credits that collected, are only from 1 grid that player look at.
and disable faction sharing, so each player can take only his credits from his ship/base.

Thanks.

**Comment by TheCrunchy** [comment]
There will be a new option in the config file to disable faction share for deposit when i release the next update

**Comment by dorimanx** [comment]
awesome, thank you!

**Comment by TheCrunchy** [comment]
Added, its enabled by default so you will need to disable it, the option is FactionShareDeposit
