### ISSUE TITLE
[Suggestion] !giveitem command gives output to the targeted player

### ISSUE THREAD

**Issue by MaceUD** [TheCrunchy/FixPlayerCommand#8]
Hey again :)

Thank you for all the previous suggestions you accepted :)

This one is when an admin or console does a `!giveitem` command and target a player, the player get a message like : *You have been given X amount of Ice*

Sincerely

**Comment by dorimanx** [comment]
Something like this :)
https://github.com/TorchAPI/Essentials/commit/e2a99d9a91e9f3d40ca8d1db8a677cc96e0fefb6
Thanks for all you have done! plugin is amazing.

**Comment by TheCrunchy** [comment]
Added
